### ISSUE TITLE
[Bug]App crashes in the Notifications screen

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#308]
### Steps to reproduce
- Tap on the bell icon
- Tap on any notification
- App crashes in the next activity
- In case it shows network error just repeat the process and the app would crash

### Expected behaviour
- App should not crash

### Actual behaviour
- App crashes

### Error Logs
```
07-19 07:24:51.366 29545-29545/io.github.project_travel_mate E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.project_travel_mate, PID: 29545
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1450)
        at java.net.SocketInputStream.read(SocketInputStream.java:169)
        at java.net.SocketInputStream.read(SocketInputStream.java:139)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:46)
        at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:352)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:396)
        at okhttp3.internal.Util.skipAll(Util.java:175)
        at okhttp3.internal.Util.discard(Util.java:157)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.close(Http1Codec.java:413)
        at okio.RealBufferedSource.close(RealBufferedSource.java:455)
        at okio.RealBufferedSource.close(RealBufferedSource.java:455)
        at okio.InflaterSource.close(InflaterSource.java:126)
        at okio.GzipSource.close(GzipSource.java:182)
        at okio.RealBufferedSource.close(RealBufferedSource.java:455)
        at okhttp3.internal.Util.closeQuietly(Util.java:110)
        at okhttp3.ResponseBody.string(ResponseBody.java:177)
        at io.github.project_travel_mate.mytrips.MyTripInfoActivity$2.lambda$onResponse$2$MyTripInfoActivity$2(MyTripInfoActivity.java:219)
        at io.github.project_travel_mate.mytrips.MyTripInfoActivity$2$$Lambda$1.run(Unknown Source:20)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by syedjahangirpeeran** [comment]
It's only applicable to older notifications which were created before the API was ready.

**Comment by Swati4star** [comment]
@knightcube I think we can close this issue, because this won't happen now.
