### ISSUE TITLE
[BUG] App crashes in Main Screen on Rotation

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#410]
### Steps to reproduce
- Main Screen i.e (Cities grid screen)
- Rotate
- App Crash

### Expected behaviour
- App should not crash

### Actual behaviour
- App Crashes

### Error Logs
```
08-05 09:42:59.649 7660-7660/io.github.project_travel_mate E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.project_travel_mate, PID: 7660
    java.lang.IllegalStateException: Fragment CityFragment{9219c7} not attached to a context.
        at android.support.v4.app.Fragment.requireContext(Fragment.java:614)
        at android.support.v4.app.Fragment.getResources(Fragment.java:678)
        at android.support.v4.app.Fragment.getString(Fragment.java:700)
        at io.github.project_travel_mate.destinations.CityFragment$3.lambda$onResponse$2$CityFragment$3(CityFragment.java:234)
        at io.github.project_travel_mate.destinations.CityFragment$3$$Lambda$1.run(Unknown Source:20)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Swati4star** [comment]
You are not supposed to push to master. You can create a Pull Request.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/420
