### ISSUE TITLE
app crashes on clickprofile

### ISSUE THREAD

**Issue by git-typecode** [project-travel-mate/Travel-Mate#449]
Travel-Mate crashes when click on profile

### Steps to reproduce
on start screen click the menu bar top left.
Click on profile
app crashes.
### Expected behaviour
Display profile?

### Actual behaviour
app crashes

### Would you like to work on the issue?
I can work on this issue.

08-27 21:49:53.526 4407-4407/io.github.project_travel_mate E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.project_travel_mate, PID: 4407
    java.lang.IllegalStateException: Could not find a method onClickProfile(View) in the activity class android.view.ContextThemeWrapper for onClick handler on view class utils.CircleImageView with id 'image'
        at android.view.View$1.onClick(View.java:4083)
        at android.view.View.performClick(View.java:4856)
        at android.view.View$PerformClick.run(View.java:19956)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:215)
        at android.app.ActivityThread.main(ActivityThread.java:5373)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
     Caused by: java.lang.NoSuchMethodException: onClickProfile [class android.view.View]
        at java.lang.Class.getMethod(Class.java:664)
        at java.lang.Class.getMethod(Class.java:643)
        at android.view.View$1.onClick(View.java:4076)
        at android.view.View.performClick(View.java:4856) 
        at android.view.View$PerformClick.run(View.java:19956) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:215) 
        at android.app.ActivityThread.main(ActivityThread.java:5373) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by Swati4star** [comment]
Sure. You can work on it!

**Comment by santoshhiremani** [comment]
Android version please, I couldn't reproduce in 7+.

**Comment by Swati4star** [comment]
@git-typecode Please provide the above info. The bug can't be reproduced, otherwise.

**Comment by git-typecode** [comment]
@santoshhiremani and @Swati4star its Lollipop 5.1.1
