### ISSUE TITLE
Crash: Unable to instantiate application

### ISSUE THREAD

**Issue by Rudloff** [project-travel-mate/Travel-Mate#57]
Hello,

I built 896f06ab7c2adaf4118218fb406de00ec3509109 from source.

When I launch, it crashes with the following error:
```
05-27 17:07:35.800  4711  4711 D AndroidRuntime: Shutting down VM
05-27 17:07:35.801  4711  4711 E AndroidRuntime: FATAL EXCEPTION: main
05-27 17:07:35.801  4711  4711 E AndroidRuntime: Process: io.github.project_travel_mate, PID: 4711
05-27 17:07:35.801  4711  4711 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application io.github.project_travel_mate.MyApplication: java.lang.IllegalAccessException: java.lang.Class<io.github.project_travel_mate.MyApplication> is not accessible from java.lang.Class<android.app.Instrumentation>
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:578)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:150)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: Caused by: java.lang.IllegalAccessException: java.lang.Class<io.github.project_travel_mate.MyApplication> is not accessible from java.lang.Class<android.app.Instrumentation>
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:997)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:982)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
05-27 17:07:35.801  4711  4711 E AndroidRuntime: 	... 9 more
05-27 17:07:35.803  2055  4332 W ActivityManager:   Force finishing activity io.github.project_travel_mate/.Splash
```

**Comment by Swati4star** [comment]
Thanks for reporting the issue! 👍

**Comment by Rudloff** [comment]
It works correctly now, thanks!
