### ISSUE TITLE
App crashed when  a click is initiated on Twitter #tags

### ISSUE THREAD

**Issue by darewealth** [project-travel-mate/Travel-Mate#644]
### Describe the bug.

The app crashed when I clicked on any #tag, on the Twitter city trends.

### Steps to reproduce.
* Launch the app.

* Clicked on any city.

* Scroll down and click on city trends 

* Then, click on any # tag

### Expected Behaviour

I was expecting to see the information that is available under the tag that I selected. 

### Screen recording
https://youtu.be/GYk_fvCxHN8

### Devices and Versions):)
* Device: [Itel]

* Version [6.1]

* App version [5.5.0]

### Log

```04-29 11:26:30.096 29889 29889 E AndroidRuntime: FATAL EXCEPTION: main
04-29 11:26:30.096 29889 29889 E AndroidRuntime: Process: io.github.project_travel_mate, PID: 29889
04-29 11:26:30.096 29889 29889 E AndroidRuntime: java.lang.IllegalArgumentException: Unknown pattern character 'Y'
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at io.github.project_travel_mate.destinations.description.TweetsDescriptionAdapter.onBindViewHolder(TweetsDescriptionAdapter.java:60)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at io.github.project_travel_mate.destinations.description.TweetsDescriptionAdapter.onBindViewHolder(TweetsDescriptionAdapter.java:26)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3225)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.View.measure(View.java:18807)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5985)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.View.measure(View.java:18807)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5985)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.View.measure(View.java:18807)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5985)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.View.measure(View.java:18807)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5985)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.View.measure(View.java:18807)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5985)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.View.measure(View.java:18807)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5985)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2659)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.View.measure(View.java:18807)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:606)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-29 11:26:30.096 29889 29889 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)```

**Comment by Swati4star** [comment]
Same as https://github.com/project-travel-mate/Travel-Mate/issues/619
