### ISSUE TITLE
App crashed when Ahmedabad or Delhi is clicked in weather forecast.

### ISSUE THREAD

**Issue by darewealth** [project-travel-mate/Travel-Mate#646]
### Describe the bug.

The app crashed when I clicked on Ahmedabad or Delhi on the select city for a weather forecast.

### Steps to reproduce.
* Launch the app.

* Clicked on menu icon.

* Then, click on utilities

* And click on the weather forecast

* Then select Delhi or Ahmedabad

* And note the bug

### Expected Behaviour

I was expecting to see the weather forecast information on any selected city   

### Screen recording
https://youtu.be/FKbIvMt2zu0

### Devices and Versions):)
* Device: [Itel]

* Version [6.1]

* App version [5.5.0]

### Log

```04-30 17:40:19.899 18568 18568 E AndroidRuntime: FATAL EXCEPTION: main
04-30 17:40:19.899 18568 18568 E AndroidRuntime: Process: io.github.project_travel_mate, PID: 18568
04-30 17:40:19.899 18568 18568 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setTint(int)' on a null object reference
04-30 17:40:19.899 18568 18568 E AndroidRuntime: 	at android.support.v4.graphics.drawable.DrawableCompat.setTint(DrawableCompat.java:135)
04-30 17:40:19.899 18568 18568 E AndroidRuntime: 	at io.github.project_travel_mate.destinations.description.WeatherActivity$1.lambda$onResponse$1(WeatherActivity.java:199)
04-30 17:40:19.899 18568 18568 E AndroidRuntime: 	at io.github.project_travel_mate.destinations.description.-$$Lambda$WeatherActivity$1$RRp9GN8-IFXugRNFKefzfPHu_bc.run(lambda)
04-30 17:40:19.899 18568 18568 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
04-30 17:40:19.899 18568 18568 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-30 17:40:19.899 18568 18568 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-30 17:40:19.899 18568 18568 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
04-30 17:40:19.899 18568 18568 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 17:40:19.899 18568 18568 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
04-30 17:40:19.899 18568 18568 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)```

**Comment by prabhakar267** [comment]
Closing this since it seems fixed!
@darewealth  Feel free to reopen if it isn't fixed
