### ISSUE TITLE
App crashed in the process of changing my password

### ISSUE THREAD

**Issue by cckole** [project-travel-mate/Travel-Mate#647]
### Description

When I tried changing my password, the app crashed

### Expected behaviour

I expected that my password would be change when I clicked on change password after I input the necessary info

### How to reproduce

After login in to the app

- Click on the menu icon by the top left side

- Click on settings. You will find it at the bottom 

- Fill the spaces and click on change password.

- Note the crash.

### Reproducting the bug

https://youtu.be/gcwxWpSwzUc

### Device used

Tecno K7

Operating system: Android 7.0

```05-06 08:42:45.254 18860 18860 E AndroidRuntime: FATAL EXCEPTION: main

05-06 08:42:45.254 18860 18860 E AndroidRuntime: Process: io.github.project_travel_mate, PID: 18860

05-06 08:42:45.254 18860 18860 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.project_travel_mate/io.github.project_travel_mate.destinations.description.RestaurantDetailsActivity}: java.lang.IllegalArgumentException: Path must not be empty.

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Path must not be empty.

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at com.squareup.picasso.Picasso.load(Picasso.java:297)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at io.github.project_travel_mate.destinations.description.RestaurantDetailsActivity.populateViews(RestaurantDetailsActivity.kt:48)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at io.github.project_travel_mate.destinations.description.RestaurantDetailsActivity.onCreate(RestaurantDetailsActivity.kt:44)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6670)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

05-06 08:42:45.254 18860 18860 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)```

**Comment by hayneek** [comment]
Can I work on this? Also, #663 seems like it's related to this issue.

**Comment by Swati4star** [comment]
Sure @hayneek

**Comment by prabhakar267** [comment]
Closing this since it seems fixed!
@cckole Feel free to reopen if it isn't fixed
