### ISSUE TITLE
App crashed when I use the notification and mark all notification. 

### ISSUE THREAD

**Issue by darewealth** [project-travel-mate/Travel-Mate#665]
### Describe the bug.

The app crashed when I  tried to use the notification and then mark all notification as read.  It happens most time when there is not any message on the notification

### Steps to reproduce.
* Launch the app.

* Click on the notification icon

* And click on the mark all icon at the top by the right 

*  It will pop up "Do you want to mark all notification as read? "

* Then click ok 

* And note the bug

### Expected Behaviour

I expect that the app should work normally and not to see a crash on the action.

### Screen recording
https://youtu.be/4w4FHgjuhI0

## Devices and Versions):)
* Device: [Gionee]

* Version [7.0]

* App version [5.5.0]

### Log
``` FATAL EXCEPTION: main
Process: io.github.project_travel_mate, PID: 26375
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=203, result=-1, data=Intent { (has extras) }} to activity {io.github.project_travel_mate/io.github.project_travel_mate.Notification}: java.lang.IllegalStateException: Notification is already initialized
 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3714)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3757)
	at android.app.ActivityThread.-wrap16(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5452)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)```

**Comment by valericaplesu** [comment]
I'm fixing it

**Comment by Swati4star** [comment]
Great @valericaplesu  👍
