### ISSUE TITLE
java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by VenomsByte** [project-travel-mate/Travel-Mate#686]
during build it shows 
	

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run

**Comment by Swati4star** [comment]
@VenomsByte The build is working fine. There is some local issue, and these logs are not clear enough to identify the issue.
